app:
  port: 8080
  mode: "debug"
  ver: "1.1.6"
  machine_id: 2
  name: "tanjunchen"
mysql:
  host: "localhost"
  port: 3306
  db: "webapp"
  user: "root"
  password: "a"
redis:
  host: "localhost"
  port: 6379
  db: 0
log:
  level: "info"
  filename: "./app.log"
  max_size: 100
  max_age: 30
  max_backups: 7

jwt:
  expire_seconds: 3600
  secret: "admin"